import { auth } from "@/auth";
import { Navigation } from "@/components/Navigation";
import { Page } from "@/components/PageLayout";
import ClientProviders from "@/providers";
import "@worldcoin/mini-apps-ui-kit-react/styles.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Template Mini App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} `}>
        <ClientProviders session={session}>
          {/* <div>{JSON.stringify(session)}</div> */}
          <Page className="bg-grey-100">
            {children}
            <Page.Footer className="px-0 fixed bottom-0 w-full bg-white">
              <Navigation />
            </Page.Footer>
          </Page>
        </ClientProviders>
      </body>
    </html>
  );
}
